# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/artem/clion/clion-2020.2.4/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/artem/clion/clion-2020.2.4/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/artem/CLionProjects/IZ1_release

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/artem/CLionProjects/IZ1_release

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/artem/clion/clion-2020.2.4/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/artem/clion/clion-2020.2.4/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/artem/CLionProjects/IZ1_release/CMakeFiles /home/artem/CLionProjects/IZ1_release/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/artem/CLionProjects/IZ1_release/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named IZ1_release

# Build rule for target.
IZ1_release: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 IZ1_release
.PHONY : IZ1_release

# fast build rule for target.
IZ1_release/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IZ1_release.dir/build.make CMakeFiles/IZ1_release.dir/build
.PHONY : IZ1_release/fast

#=============================================================================
# Target rules for targets named runTests

# Build rule for target.
runTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 runTests
.PHONY : runTests

# fast build rule for target.
runTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/build
.PHONY : runTests/fast

list_functions.o: list_functions.c.o

.PHONY : list_functions.o

# target to build an object file
list_functions.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IZ1_release.dir/build.make CMakeFiles/IZ1_release.dir/list_functions.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/list_functions.c.o
.PHONY : list_functions.c.o

list_functions.i: list_functions.c.i

.PHONY : list_functions.i

# target to preprocess a source file
list_functions.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IZ1_release.dir/build.make CMakeFiles/IZ1_release.dir/list_functions.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/list_functions.c.i
.PHONY : list_functions.c.i

list_functions.s: list_functions.c.s

.PHONY : list_functions.s

# target to generate assembly for a file
list_functions.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IZ1_release.dir/build.make CMakeFiles/IZ1_release.dir/list_functions.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/list_functions.c.s
.PHONY : list_functions.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IZ1_release.dir/build.make CMakeFiles/IZ1_release.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IZ1_release.dir/build.make CMakeFiles/IZ1_release.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IZ1_release.dir/build.make CMakeFiles/IZ1_release.dir/main.c.s
.PHONY : main.c.s

ship_functions.o: ship_functions.c.o

.PHONY : ship_functions.o

# target to build an object file
ship_functions.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IZ1_release.dir/build.make CMakeFiles/IZ1_release.dir/ship_functions.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/ship_functions.c.o
.PHONY : ship_functions.c.o

ship_functions.i: ship_functions.c.i

.PHONY : ship_functions.i

# target to preprocess a source file
ship_functions.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IZ1_release.dir/build.make CMakeFiles/IZ1_release.dir/ship_functions.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/ship_functions.c.i
.PHONY : ship_functions.c.i

ship_functions.s: ship_functions.c.s

.PHONY : ship_functions.s

# target to generate assembly for a file
ship_functions.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IZ1_release.dir/build.make CMakeFiles/IZ1_release.dir/ship_functions.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/ship_functions.c.s
.PHONY : ship_functions.c.s

test.o: test.cpp.o

.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i

.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s

.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/test.cpp.s
.PHONY : test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... IZ1_release"
	@echo "... runTests"
	@echo "... list_functions.o"
	@echo "... list_functions.i"
	@echo "... list_functions.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... ship_functions.o"
	@echo "... ship_functions.i"
	@echo "... ship_functions.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

